<title><?=$design_info->site_title?></title>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<meta name="keywords" content="<?=$design_info->site_keyword?>">
<meta name="description" content="<?=$design_info->site_intro?>">
<meta name="robots" content="index, follow">
<meta name="GOOGLEBOT" content="INDEX, FOLLOW">
<meta http-equiv="imagetoolbar" content="no"> 

<script language='JavaScript'>
<!--
function bluring(){
if(event.srcElement.tagName=="A"||event.srcElement.tagName=="IMG") document.body.focus();
}
document.onfocusin=bluring;
-->
</script>
